name: CPU Load Test

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Duration in minutes (1-30)'
        required: true
        default: '5'
      concurrency:
        description: 'Number of simultaneous jobs (1-10)'
        required: true
        default: '3'
      cpu_load:
        description: 'CPU load percentage (10-100)'
        required: true
        default: '80'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          # Create array with indexes from 0 to concurrency-1
          echo "matrix=[$(seq -s ',' 0 $((${{ github.event.inputs.concurrency }}-1)))]" >> $GITHUB_OUTPUT
          
  cpu-load-test:
    needs: prepare-matrix
    runs-on: [self-hosted, linux, x64]
    strategy:
      fail-fast: false
      matrix:
        instance: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run CPU load
        run: |
          bash ./scripts/cpu_load.sh ${{ github.event.inputs.duration }} ${{ github.event.inputs.cpu_load }}