name: Process Single Job

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job identifier'
        required: true
      duration:
        description: 'Duration in minutes'
        required: true

jobs:
  run-job:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run job
        run: |
          echo "Running job ${{ github.event.inputs.job_id }} for ${{ github.event.inputs.duration }} minutes"
          
          # Install bc for calculations
          sudo apt-get update -qq && sudo apt-get install -y bc
          
          # Calculate seconds and remove decimal part for timeout
          SECONDS=$(echo "${{ github.event.inputs.duration }} * 60" | bc | cut -d. -f1)
          
          # Run the job
          timeout "$SECONDS" \
            bash -c 'while true; do echo "Working..." > /dev/null; dd if=/dev/zero of=/dev/null bs=1M count=10; sleep 0.1; done'